# Generated by Django 5.0.3 on 2024-03-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_all_books_home_all_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('home_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.home')),
                ('book_name', models.CharField(max_length=100)),
            ],
            bases=('home.home',),
        ),
    ]
