# Generated by Django 5.0.3 on 2024-03-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
