# Generated by Django 5.0.3 on 2024-05-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usersinfos_delete_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinfos',
            name='username',
        ),
    ]
