# Generated by Django 5.0.3 on 2024-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_usersinfos_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfos',
            name='total_books',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AddField(
            model_name='usersinfos',
            name='total_pages_read',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
