# Generated by Django 5.0.3 on 2024-05-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_usersinfos_total_books_usersinfos_total_pages_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_text', models.CharField(max_length=200)),
                ('date_posted', models.DateField(auto_now=True)),
                ('post_picture', models.ImageField(blank=True, upload_to='posts/%Y/%m/')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
