# Generated by Django 5.0.3 on 2024-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='simple_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
