# Generated by Django 5.0.3 on 2024-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_post_autor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfos',
            name='total_books',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersinfos',
            name='total_pages_read',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
