# Generated by Django 5.0.3 on 2024-05-23 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_usersinfos_total_books_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_book', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('number_pages', models.PositiveBigIntegerField(default=0)),
                ('owner_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('fixed', models.BooleanField(default=False)),
                ('owner_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.post')),
            ],
        ),
    ]
