# Generated by Django 5.0.3 on 2024-05-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_postcomments_owner_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcaseuser',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookcaseuser',
            old_name='img_book',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='bookcaseuser',
            old_name='owner_book',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor_post',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_picture',
            new_name='picture',
        ),
    ]
