# Generated by Django 5.0.3 on 2024-05-26 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_autor_bookcaseuser_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
        migrations.RenameModel(
            old_name='UsersInfos',
            new_name='UsersInfo',
        ),
    ]
