# Generated by Django 5.0.3 on 2024-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_postcomments_postcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcaseuser',
            name='img',
            field=models.ImageField(blank=True, upload_to='bookcase/%Y/%m/'),
        ),
    ]
